spring.application.name=Interview-Simulator

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update

server.port=8096

gemini.ai.key=${GEMINI_API_KEY}
groq.ai.key=${GROQ_API_KEY}