spring.application.name=Interview-Simulator

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

gemini.ai.key=${GEMINI_API_KEY}
groq.ai.key=${GROQ_API_KEY}